name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: install pnpm
      run: |
        npm install -g pnpm@5.x
        pnpm --version
    - name: pnpm install
      run: pnpm recursive install
    - name: lint
      run: pnpm run lint
    - name: test
      run: pnpm run -r test
